import type { Metadata } from "next";
import { Space_Grotesk } from "next/font/google";
import "./globals.css";

const Space_Grotesk_font = Space_Grotesk({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={Space_Grotesk_font.className}> {children}</body>
    </html>
  );
}
